jeroen_ed_cms_ed:
    resource: "@JeroenEDCmsEDBundle/Controller/"
    type:     annotation
    prefix:   /admin

jeroen_ed_portfolio:
    resource: "@JeroenEDPortfolioBundle/Controller/"
    type:     annotation
    prefix:   /

