jeroen_ed_cms_ed:
    resource: "@JeroenEDCmsEDBundle/Controller/"
    type:     annotation
    prefix:   /

jeroen_ed_portfolio:
    resource: "@JeroenEDPortfolioBundle/Controller/"
    type:     annotation
    prefix:   /

