jeroen_ed_cms_ed:
    resource: "@JeroenEDCmsEDBundle/Controller/"
    type:     annotation
    prefix:   /

jeroen_ed_portfolio:
    resource: "@JeroenEDPortfolioBundle/Controller/"
    type:     annotation
    prefix:   /

lib_kcfinder: 
    resource: "@libKCFinderBundle/Resources/config/routing.yml" 
    prefix: /