jeroen_ed_cms_ed:
    resource: "@JeroenEDCmsEDBundle/Controller/"
    type:     annotation
    prefix:   /

jeroen_ed_portfolio:
    resource: "@JeroenEDPortfolioBundle/Controller/"
    type:     annotation
    prefix:   /

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
    prefix: /admin